[phases.setup]
nixPackages = ["python3", "gcc", "make", "python3.sitePackages.pip"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start"