
services:
  postgres:
    image: postgres:latest
    container_name: bijlee_db
    environment:
      POSTGRES_USER: bijlee_user
      POSTGRES_PASSWORD: bijlee_password
      POSTGRES_DB: bijlee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: